# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/file.proto
# Protobuf Python Version: 6.31.1
"""
Generated protocol buffer code.
  - file_pb2.py: 우리가 정의한 FileChunk, FileInfo 같은 메시지 클래스
"""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "protos/file.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x11protos/file.proto\x12\x04\x66ile"I\n\tFileChunk\x12\x1e\n\x04info\x18\x01 \x01(\x0b\x32\x0e.file.FileInfoH\x00\x12\x14\n\nchunk_data\x18\x02 \x01(\x0cH\x00\x42\x06\n\x04\x64\x61ta"/\n\x08\x46ileInfo\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x11\n\tfile_type\x18\x02 \x01(\t"A\n\x0cUploadStatus\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07\x66ile_id\x18\x03 \x01(\t2D\n\x0b\x46ileService\x12\x35\n\nUploadFile\x12\x0f.file.FileChunk\x1a\x12.file.UploadStatus"\x00(\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "protos.file_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_FILECHUNK"]._serialized_start = 27
    _globals["_FILECHUNK"]._serialized_end = 100
    _globals["_FILEINFO"]._serialized_start = 102
    _globals["_FILEINFO"]._serialized_end = 149
    _globals["_UPLOADSTATUS"]._serialized_start = 151
    _globals["_UPLOADSTATUS"]._serialized_end = 216
    _globals["_FILESERVICE"]._serialized_start = 218
    _globals["_FILESERVICE"]._serialized_end = 286
# @@protoc_insertion_point(module_scope)
